version: "3.4"
services:
  overlord:
    image: overlord-docker:latest
    build:
      context: .
      network: host
      x-bake:
        tags:
          - overlord-docker:latest
          - overlord-docker:${TAG}
    container_name: overlord-docker
    network_mode: host
    environment:
      - TZ=Australia/Brisbane
      - OVERLORD_CONFIG_FILE=overlord.conf
