version: "3.4"
services:
  overlord:
    image: overlord:latest
    restart: always
    build:
      context: .
      network: host
      x-bake:
        tags:
          - overlord:latest
          - overlord:${TAG:-0.1}
    container_name: overlord
    volumes:
      - type: bind
        source: /var/docker/motion-data
        target: /var/lib/motion
    networks:
      - overworld-network
    environment:
      - TZ=Australia/Brisbane
      - OVERLORD_CONFIG_FILE=overlord.conf

networks:
  overworld-network:
    external: true

